#language: java
#jdk:
#  - openjdk8
#
#branches:
#  only:
#    - master
#
#cache:
#  directories:
#    - '$HOME/.m2/repository'
#    - '$HOME/.gradle'
#
#script: "./gradlew clean build"

language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew clean build
after_success:
  - ./gradlew jacocoRootReport coveralls